apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-privileged-disallowed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-privileged
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: nginx-privileged
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: nginx
        image: nginx     
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
