apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default.test-gitops
spec:
  tier: default
  selector: projectcalico.org/namespace == "tigera-manager"
  namespaceSelector: ''
  serviceAccountSelector: ''
  ingress:
    - action: Allow
      source:
        selector: all()
      destination: {}
  egress:
    - action: Allow
      source: {}
      destination:
        selector: all()
  doNotTrack: false
  applyOnForward: false
  preDNAT: false
  types:
    - Ingress
    - Egress
